### ISSUE TITLE
Test failures with both Python 2.7/3.5

### ISSUE THREAD

**Issue by felixonmars** [davidvilla/python-doublex#3]
I am getting the following test failures, please have a look:

Python 3.5:
```
======================================================================
ERROR: test_fail_on_unexpected_call_msg_is_human_readable (doublex.test.pyDoubles.unit_tests.MockTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex/build/lib/doublex/test/pyDoubles/unit_tests.py", line 487, in test_fail_on_unexpected_call_msg_is_human_readable
    self.mock.hello()
  File "/build/python-doublex/src/python-doublex/build/lib/doublex/internal.py", line 100, in __call__
    retval = self.double._manage_invocation(invocation)
  File "/build/python-doublex/src/python-doublex/build/lib/doublex/doubles.py", line 78, in _manage_invocation
    self._prepare_invocation(invocation)
  File "/build/python-doublex/src/python-doublex/build/lib/doublex/doubles.py", line 152, in _prepare_invocation
    hamcrest.assert_that(self, MockIsExpectedInvocation(invocation))
  File "/usr/lib/python3.5/site-packages/hamcrest/core/assert_that.py", line 43, in assert_that
    _assert_match(actual=arg1, matcher=arg2, reason=arg3)
  File "/usr/lib/python3.5/site-packages/hamcrest/core/assert_that.py", line 57, in _assert_match
    raise AssertionError(description)
AssertionError:
Expected: these calls:
          No one
     but: this call was not expected:
          Collaborator.hello()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex/build/lib/doublex/test/pyDoubles/unit_tests.py", line 490, in test_fail_on_unexpected_call_msg_is_human_readable
    if re.search("No one", arg):
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

======================================================================
ERROR: test_fail_incorrect_times_msg_is_human_readable (doublex.test.pyDoubles.unit_tests.ProxySpyTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex/build/lib/doublex/test/pyDoubles/unit_tests.py", line 318, in test_fail_incorrect_times_msg_is_human_readable
    assert_that_method(self.spy.one_arg_method).was_called().times(5)
  File "/build/python-doublex/src/python-doublex/build/lib/doublex/pyDoubles/__init__.py", line 163, in times
    hamcrest.greater_than_or_equal_to(n)))
  File "/usr/lib/python3.5/site-packages/hamcrest/core/assert_that.py", line 43, in assert_that
    _assert_match(actual=arg1, matcher=arg2, reason=arg3)
  File "/usr/lib/python3.5/site-packages/hamcrest/core/assert_that.py", line 57, in _assert_match
    raise AssertionError(description)
AssertionError:
Expected: these calls:
          Collaborator.one_arg_method(ANY_ARG) -- times: a value greater than or equal to <5>
     but: calls that actually ocurred were:
          Collaborator.one_arg_method(1)-> 1


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex/build/lib/doublex/test/pyDoubles/unit_tests.py", line 322, in test_fail_incorrect_times_msg_is_human_readable
    if re.search("5", arg) and re.search("one_arg_method", arg):
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

======================================================================
FAIL: test_matcher_error_is_human_readable (doublex.test.pyDoubles.hamcrest_integration_tests.HamcrestIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex/build/lib/doublex/test/pyDoubles/hamcrest_integration_tests.py", line 76, in test_matcher_error_is_human_readable
    starts_with('tt'))
AssertionError:
Expected: these calls:
          Collaborator.one_arg_method(a string starting with 'tt')
     but: calls that actually ocurred were:
          Collaborator.one_arg_method('xe')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex/build/lib/doublex/test/pyDoubles/hamcrest_integration_tests.py", line 78, in test_matcher_error_is_human_readable
    self.assertTrue("tt" in str(e.args))
AssertionError: False is not true

======================================================================
FAIL: test_if_doesnt_match_message_is_human_redable (doublex.test.pyDoubles.unit_tests.MatchersTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex/build/lib/doublex/test/pyDoubles/unit_tests.py", line 780, in test_if_doesnt_match_message_is_human_redable
    str_containing("xxx"))
AssertionError:
Expected: these calls:
          Collaborator.one_arg_method(a string containing 'xxx')
     but: calls that actually ocurred were:
          Collaborator.one_arg_method('XabcX')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex/build/lib/doublex/test/pyDoubles/unit_tests.py", line 783, in test_if_doesnt_match_message_is_human_redable
    self.assertTrue("xxx" in str(e.args), str(e.args))
AssertionError: False is not true : (<hamcrest.core.string_description.StringDescription object at 0x7fa0fa1a0d30>,)

----------------------------------------------------------------------
Ran 425 tests in 1.692s

FAILED (failures=2, errors=2)
```

Python 2.7:
```
======================================================================
ERROR: test_fail_on_unexpected_call_msg_is_human_readable (doublex.test.pyDoubles.unit_tests.MockTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex-py2/doublex/test/pyDoubles/unit_tests.py", line 490, in test_fail_on_unexpected_call_msg_is_human_readable
    if re.search("No one", arg):
  File "/usr/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer

======================================================================
ERROR: test_fail_incorrect_times_msg_is_human_readable (doublex.test.pyDoubles.unit_tests.ProxySpyTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex-py2/doublex/test/pyDoubles/unit_tests.py", line 322, in test_fail_incorrect_times_msg_is_human_readable
    if re.search("5", arg) and re.search("one_arg_method", arg):
  File "/usr/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer

======================================================================
FAIL: test_matcher_error_is_human_readable (doublex.test.pyDoubles.hamcrest_integration_tests.HamcrestIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex-py2/doublex/test/pyDoubles/hamcrest_integration_tests.py", line 78, in test_matcher_error_is_human_readable
    self.assertTrue("tt" in str(e.args))
AssertionError: False is not true

======================================================================
FAIL: test_if_doesnt_match_message_is_human_redable (doublex.test.pyDoubles.unit_tests.MatchersTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex-py2/doublex/test/pyDoubles/unit_tests.py", line 783, in test_if_doesnt_match_message_is_human_redable
    self.assertTrue("xxx" in str(e.args), str(e.args))
AssertionError: (<hamcrest.core.string_description.StringDescription object at 0x7fd39da209d0>,)

----------------------------------------------------------------------
Ran 425 tests in 1.612s

FAILED (failures=2, errors=2)
```

**Comment by davidvilla** [comment]
Thank you very much for your feedback. I will see as soon as possible.

**Comment by davidvilla** [comment]
Hi:

The failing tests were just about exception message printing. So there was no functional problems at all.
It was a change in type hamcrest.core.string_description.StringDescription that does not allow to evaluate as strings. The tests will be fixed in next release.

Thanks

**Comment by felixonmars** [comment]
I see, thank you. Looking forward to next release :)
