### ISSUE TITLE
Does not build on python 3.7 due to use of the reserved keyword "async", tests completely broken

### ISSUE THREAD

**Issue by eli-schwartz** [davidvilla/python-doublex#7]
On the tests, trying to run them aborts immediately on python3.6 with

```
======================================================================
ERROR: test3 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test3
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'doublex.test3'

```

python2.7 fails with:

```
======================================================================
ERROR: test_hack_function_spy (doublex.test.unit_tests.function_doubles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex-py2/doublex/test/unit_tests.py", line 1718, in test_hack_function_spy
    method = Method(stub, 'orphan')
NameError: global name 'Method' is not defined

----------------------------------------------------------------------
Ran 426 tests in 1.602s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=426 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=426 errors=1 failures=0>
```

**Comment by davidvilla** [comment]
Hi:

Thanks a lof for your feedback. The py36 failing test is now OK. I can not replicate the py27 test fail. All test work on py27, py35 and py36.

You can get at https://bitbucket.org/DavidVilla/python-doublex-hg and in the next 1.9.0 version, I am trying to migrate repository to git.

Best regards

**Comment by eli-schwartz** [comment]
The tests now pass for me on the new release with python 3.6 and 2.7.

However, it is still broken on python 3.7 due to using the reserved keyword "async". See https://www.python.org/dev/peps/pep-0492/ for more details.

```
$ pip install --user doublex
...
Successfully installed doublex-1.9.0
$ python -c 'import doublex'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/build/.local/lib/python3.7/site-packages/doublex/__init__.py", line 3, in <module>
    from .doubles import *
  File "/build/.local/lib/python3.7/site-packages/doublex/doubles.py", line 29, in <module>
    from .matchers import MockIsExpectedInvocation
  File "/build/.local/lib/python3.7/site-packages/doublex/matchers.py", line 129
    def async(self, timeout):
            ^
SyntaxError: invalid syntax
```

Or from the testsuite:

```
['doublex', 'doublex.test', 'doublex.test3', 'doublex.test3.test']
running test
running egg_info
creating doublex.egg-info
writing doublex.egg-info/PKG-INFO
writing dependency_links to doublex.egg-info/dependency_links.txt
writing requirements to doublex.egg-info/requires.txt
writing top-level names to doublex.egg-info/top_level.txt
writing manifest file 'doublex.egg-info/SOURCES.txt'
reading manifest file 'doublex.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'doublex.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 77, in <module>
    setup(**config)
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/usr/lib/python3.7/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/usr/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.7/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/lib/python3.7/unittest/main.py", line 159, in createTests
    self.module)
  File "/usr/lib/python3.7/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.7/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/build/python-doublex/src/python-doublex/doublex/__init__.py", line 3, in <module>
    from .doubles import *
  File "/build/python-doublex/src/python-doublex/doublex/doubles.py", line 29, in <module>
    from .matchers import MockIsExpectedInvocation
  File "/build/python-doublex/src/python-doublex/doublex/matchers.py", line 129
    def async(self, timeout):
            ^
SyntaxError: invalid syntax
```

**Comment by eli-schwartz** [comment]
Fixing this essentially requires changing the public API of doublex.matchers.MethodCalled.

**Comment by eli-schwartz** [comment]
If I try renaming the function to, e.g. "wait()" then the tests execute and all tests pass, except for one error:

```
FAIL: test_builtin_method_wrong_num_args (doublex.test3.test.unit_tests.BuiltinSpyTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-doublex/src/python-doublex/doublex/test3/test/unit_tests.py", line 462, in test_builtin_method_wrong_num_args
    self.fail('AttributeError should be raised')
AssertionError: AttributeError should be raised

----------------------------------------------------------------------
Ran 216 tests in 1.532s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=216 errors=0 failures=1>
```
